owner: Javier-Jimenez99
repo: tr3cks-webmonitor

sites:
  - name: App Frontend (React)
    url: https://animdle.com
    check-status-codes: [200]
  
  - name: API Backend (Django)
    url: https://api.animdle.com/health/
    method: GET
    expected-status: 200

notifications:
  - type: telegram

workflow-schedule:
  graphs: "0 0 * * *"
  static-site: "0 1 * * *"
  summary: "0 0 * * *"
  uptime: "*/5 * * * *" # Each 5 minutes

navbar:
  - title: Status
    href: /tr3cks-webmonitor/
